name: GitHub Actions Docker publish
run-name: ${{ github.actor }} has triggered Docker publish ðŸš€
on:
  pull_request:
    types:
      - closed

jobs:
  push_backend_to_registery:
    name: Push Docker image to Docker Hub
    if: github.event.pull_request.merged # Ensure PR is merged
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push backend Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./Backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.event.pull_request.ref }}, ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Build and push frontend Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./Frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.event.pull_request.ref }}, ${{ secrets.DOCKER_USERNAME }}/frontend:latest
                
      - name: Build and push nginx Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./nginx
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/rproxy:${{ github.event.pull_request.ref }}, ${{ secrets.DOCKER_USERNAME }}/rproxy:latest