name: Review pipeline
run-name: ${{ github.ref_name }} review pipeline

on: [push]

jobs:
  Review-pipeline:
    name: Review pipeline
    runs-on: ubuntu-latest
    env:
      NODE_COVERALLS_DEBUG: 1
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          touch .env
          echo AWS_GIT_TOKEN=${{ secrets.AWS_GIT_TOKEN }} >> .env
          echo AWS_GIT_TOKEN=${{ secrets.AWS_GIT_TOKEN }} >> Backend/.env

      - name: Run frontend tests
        working-directory: ./Frontend
        run: |
          npm install --silent
          npm run test

      - name: Run backend tests
        working-directory: ./Backend
        run: |
          npm install --silent
          mkdir ./coverage
          mkdir ./coverage/tmp
          npm run coveralls-report

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: "./Backend/coverage/lcov.info"