name: Review pipeline
run-name: ${{ github.ref_name }} review pipeline

on: [push]

jobs:
  Review-pipeline:
    name: Review pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create .env file
        run: |
          touch .env
          echo AWS_GIT_TOKEN=${{ secrets.AWS_GIT_TOKEN }} >> .env
          echo AWS_GIT_TOKEN=${{ secrets.AWS_GIT_TOKEN }} >> Backend/.env
      - name: Install dependencies
        working-directory: ./Backend
        run: npm install 

      - name: Run tests and check test coverage
        working-directory: ./Backend
        run: npm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@1.1.3
        with:
          github-token: ${{ secrets.github_token }}
          #path-to-lcov: "./coverage/"

